### ISSUE TITLE
About the result from model trained from scratch?

### ISSUE THREAD

**Issue by QiHuangChen** [rafellerc/Pytorch-SiamFC#2]
Thank you for the job! Can you show the results on you machine? Thank you for your reply.

**Comment by rafellerc** [comment]
Hi, I'm currently working on that and I'll be soon posting some of the results and rewrite some of the README file.

**Comment by rafellerc** [comment]
@QiHuangChen  I added the results of the training part. I'll work to debug and present the results of the tracker part soon.
