### ISSUE TITLE
AssertionError: [IMAGE-UTILS] Error: It seems that the used image utils flag is not available, try setting the flag to 'safe'.

### ISSUE THREAD

**Issue by wtc813** [rafellerc/Pytorch-SiamFC#27]
>>python train.py --data_dir ~/ILSVRC/ --exp_name mytest 
[IMAGE-UTILS] package jpeg4py not available. Continuing...
----Starting train script in mode: train----
Loading datasets...
Traceback (most recent call last):
  File "train.py", line 526, in <module>
    main(args)
  File "train.py", line 107, in main
    img_read_fcn = imutils.get_decode_jpeg_fcn(flag=args.imutils_flag)
  File "/home/tcw/Mask/Pytorch-SiamFC-master/utils/image_utils.py", line 60, in get_decode_jpeg_fcn
    assert LIBJPEG_TURBO_PRESENT, ('[IMAGE-UTILS] Error: It seems that the '
AssertionError: [IMAGE-UTILS] Error: It seems that the used image utils flag is not available, try setting the flag to 'safe'.

Can someone help me solve this problem? Thank you.

**Comment by ClementPinard** [comment]
The default img loader tries to use libjpeg turbo to accelerate data loading. It's not automatically installed and you have to get it manually, hence the error.

By using the safe flag, you use instead the imageio library, which is slower, but in most cases is enough for data loading not to be the speed bottleneck.

https://libjpeg-turbo.org/
