### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by CXSunshine** [rafellerc/Pytorch-SiamFC#28]
FileNotFoundError: The file ../my_SiameseFC_pytorch/Imagenet2015/Annotations/VID/train/ILSVRC2015_VID_train_0000/ILSVRC2015_train_00000000/.ipynb_checkpoints.xml could not be found。
why this file is needed?

**Comment by CXSunshine** [comment]
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 266 and 255 in dimension 2 at /opt/conda/conda-bld/pytorch_1556653099582/work/aten/src/TH/generic/THTensor.cpp:711

**Comment by CXSunshine** [comment]
- Eval metrics : AUC: 0.939 ; center_error: 12.549 ; loss: 763.956
Checkpoint Directory exists! 
- Found new best auc
=== Execution exited normally ===
loss in not

**Comment by xujinzh** [comment]
delete 'Annotations/VID/train/ILSVRC2015_VID_train_0000/ILSVRC2015_train_00000000/.ipynb_checkpoints' solved my problem

or 

in file 'training/datasets.py' change codes
```python      
for frame in sorted(os.listdir(join(self.dir_data, sequence))):
```
to
```python
frame_path = join(self.dir_data, sequence)
frame_list = [frame for frame in os.listdir(frame_path) if isfile(join(frame_path, frame))]
for frame in sorted(frame_list):
```
